// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDELE9B2scDKplunAJOe8VZEdQUvznkXkk",
    authDomain: "communitrade-449ae.firebaseapp.com",
    projectId: "communitrade-449ae",
    storageBucket: "communitrade-449ae.appspot.com",
    messagingSenderId: "753334474052",
    appId: "1:753334474052:web:bc4babf4fa9edc7e823311"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbLAN3xUqOeb72AvcNWl6OiCH0Pa7N8mQ',
    appId: '1:753334474052:android:8e868e0cfac3f67e823311',
    messagingSenderId: '753334474052',
    projectId: 'communitrade-449ae',
    storageBucket: 'communitrade-449ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9IYbZR4HwALg6aYnh_v8MctozZet6bsg',
    appId: '1:753334474052:ios:0e968dd43d585972823311',
    messagingSenderId: '753334474052',
    projectId: 'communitrade-449ae',
    storageBucket: 'communitrade-449ae.appspot.com',
    iosBundleId: 'com.example.communitrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9IYbZR4HwALg6aYnh_v8MctozZet6bsg',
    appId: '1:753334474052:ios:2c64925825cf1275823311',
    messagingSenderId: '753334474052',
    projectId: 'communitrade-449ae',
    storageBucket: 'communitrade-449ae.appspot.com',
    iosBundleId: 'com.example.communitrade.RunnerTests',
  );
}
